[general]
import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.95
dynamic_title = true
dynamic_padding = true

[window.padding]
x = 12
y = 12

[window.dimensions]
columns = 108
lines = 28

[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }
size = 11

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true
thickness = 0.15
blink_interval = 750

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
    { key = "N", mods = "Command|Shift", action = "CreateNewWindow" }
]