name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install shfmt
      run: |
        sudo apt-get update
        sudo apt-get install -y shfmt
        
    - name: Check format
      run: |
        shfmt -d -i 4 -ci pomarchy $(find src -name "*.sh" -o -name "*.bash")
        
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        
    - name: Run lint
      run: make lint
      
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install bats
      run: |
        sudo apt-get update
        sudo apt-get install -y bats
        
    - name: Run tests
      run: make test
